### PR TITLE
 Add feature: Render projects list as tree structure that generated from some path-liked project name.

### PR DESCRIPTION
**Pull request by luozhihua**
image

### CODE REVIEW

**Comment by alefragnani** [comment]
Hi @luozhihua ,

First of all, thank you for your PR 👍 .

I didn't have free time to test it yet, but one thing that I missed was a **setting** to be able to _enable/disable_ this behavior. I mean, even being an interesting feature, personally, I prefer the original behavior..

I also didn't see anything related to `Context Menu` commands in treeview. Since you created a tree view, you have _leafs_ and _forks_ as two separate entities, and the `Context Menu` commands that exists today can't be run in _forks_.

Could you make the updates?

**Comment by alefragnani** [comment]
Last week I decided to "re-focus" on some of my extensions, and I'll start to plan milestones for each of them. This "re-focus" will be based on community feedback/support.

I’m closing this PR because I have a different vision on how the projects could be organized/grouped, so unfortunately, it couldn’t be used/merged on master.

Thank you for time and effort creating this issue. I’ll let you know if something changes in the future.

**Comment by leandro-manifesto** [comment]
Any news on this?

I could use a button like the Source Control side bar where we toggle between a list and a tree.

**Comment by alefragnani** [comment]
Hi @leandro-manifesto ,

It’s being tracked in #50 , and I’m planning for the upcoming releases

Hope this helps

**Pull request closed without merging**
