### PR TITLE
 Created community, add badges and improving the layout

### PR DESCRIPTION
**Pull request by mittalyashu**
image

### CODE REVIEW

**Comment by alefragnani** [comment]
Hi @mittalyashu ,

First of all, thanks for your PR. 

I don't know if I would merge all your suggestions, but it will certainly be used to improve the layout. Specially about the _badges_, there are some [restrictions](https://code.visualstudio.com/docs/extensionAPI/extension-manifest#_approved-badges), and wouldn't be able to use all of them. BTW, I don't know Spectrum Chat, have you created that? 😄  

Thank you

**Comment by mittalyashu** [comment]
The download badge had a static value, I didn't find the way to fetch the downloads from the Microsoft extension website.

> there are some restrictions, and wouldn't be able to use all of them

You have mentioned about the restriction, I have checked the list and all the badges I have added should work since we are using [shields.io](https://shields.io).

> BTW, I don't know Spectrum Chat, have you created that? 😄

Yes, I have created that community on Spectrum, if you want I can transfer the [ownership to you](https://spectrum.chat/thread/3cc448a2-5845-4992-a70a-9e317f56e0c0?m=MTUzNTA0OTU0MjMyNw==) anytime.

You can [join the community](https://spectrum.chat/vscode-project-manager), create threads and [explore the spectrum universe](https://spectrum.chat/explore).

**Comment by mittalyashu** [comment]
In slack and Gitter, the conversation can easily get mixed up.

In spectrum the conversation is organised into thread and there is no limit to the history just like slack.

Recently [Zeit has officially announced](https://zeit.co/blog/spectrum) that they are moving from slack to Spectrum.

**Comment by alefragnani** [comment]
Last week I decided to "re-focus" on some of my extensions, and I'll start to plan milestones for each of them. This "re-focus" will be based on community feedback/support.

I’m closing this PR because I have a different vision about the Readme page, and unfortunately not all your changes can be used/merged in master. But specifically the badges, I should borrow some :-)

Thank you for time and effort creating this PR.

**Pull request closed without merging**
