### PR TITLE
load projects when the Projects.json file change

### PR DESCRIPTION
**Pull request by likun7981**
The load project action only when we start vscode , so each time we modify the __Projects.json__  need to restart vscode.We should load  the  __Projects.json__ when we excute the list command

### CODE REVIEW

**Comment by likun7981** [comment]
I am sorry , I use format , you can ignore some space in the code

**Comment by likun7981** [comment]
Maybe we should add a command that named __reload projects__.

**Comment by alefragnani** [comment]
Hi @likun7981 ,

First of all, I'm sorry for taking so long to answer your PR, and thanks, by the way 👍 

Instead of loading the `projects.json` file each time the `List` command is executed, I think a better option is to use a `FileSystemWatcher`. At least this was my idea to fix the `projects.json` caching for https://github.com/alefragnani/vscode-project-manager/issues/85, and use `onDidChangeConfiguration` for VSCode/Git/SVN projects settings. Also, removing the loadProjects from activation would make the StatusBar feature stop working. It is still necessary there 😢 .

Would you be willing to change your PR to use a `FileSystemWatcher`? If yes, I could wait for it and merge with the `onDidChangeConfiguration` updates, and fix that issue sooner. 

What do you think about it?

**Comment by likun7981** [comment]
I have finish it, watch the __Projects.json__. use [chokidar](https://github.com/paulmillr/chokidar). when it changed , we will reload it

**Comment by likun7981** [comment]
I use format code tool, So the code will have many spaces because we do not have the same code style , if you need. I will recover code as before

**Comment by likun7981** [comment]
I think you can add __eslint__ . how about it?

**Comment by alefragnani** [comment]
Thanks @likun7981 ,

I came from a Delphi background, so I didn't decide my TS/JS style _yet_. That's why I added TSLint to the project sometime ago. Doing so, it will help me to _decide_ my _coding style_. Some of the changes you made will be automatically updated when I merge the project, and the others, well, let's see 😄 . Don't worry 👍 .

I thought you could use the `FileSystemWatcher` interface, available in VSCode API, instead of `chokidar` itself, but internally, it appears to be the same, so no problem too :)

It should be merged/updated tomorrow.

**Comment by alefragnani** [comment]
I just noted why `FileSystemWatcher` could not be used. It works only for _in workspace files_, and since `package.json` is an _external file_, it doesn't work.

Any reason why you used `chokidar` instead of `fs.watchFile`? I mean, `chokidar` seems to be powerfull, but for some reason, it is not allowing me to publish the extension. It seems related to _its dependencies_, in particularly `fsevents`, which appears to be _non-Windows friendly_ (my OS). Which OS are you using?

I tested `fs.watchFile`, and it works as expected. If it works for you, I pretend to replace `chokidar`. Could you test in you machine?

**Comment by likun7981** [comment]
`fs.watch` biggest drawback is that subfolders are not supported。Many __Editors__ will clear file first, and then save. it will trigger two folder(file) change events. the `chokidar` help us deal with this shortcoming. I will try using `fs.watch`  with Mac OS . You wait.

**Comment by alefragnani** [comment]
Well, we are watching a single file, not folders so, it may not be an issue for us.

Let me know if it works on MacOS. The code is already prepared to publish :smile:

**Comment by likun7981** [comment]
I test `fs.watchFile` that is normal on Mac os , but the node doc said `fs.watch` is more efficient than `fs.watchFile`.  we only watch __Projects.json__ file.  so we can use `fs.watchFile`.

**Pull request merged**
