### PR TITLE
Make sorting more natural, where capital and lowercase letters are equal

### PR DESCRIPTION
**Pull request by lavir**

### CODE REVIEW

**Comment by alefragnani** [comment]
Hi @lavir ,

First of all, thanks for your PR 👍 . 

That's a good enhancement. I'm just wondering if this should be _OS dependent_, since Windows is case-insensitive, but MacOS and Linux are case-sensitive.

**Comment by lavir** [comment]
I think that this does not matter. The PR "fixing" the case-sensitive in MacOS and Linux, at the same time this fix does not change behavior on Windows.

**Comment by bdougherty** [comment]
MacOS is case sensitive, but the Finder does a case-insensitive sort (I believe that it's the same way on Linux too), so I think this is a good change 👍

**Comment by alefragnani** [comment]
I understand that, and in fact, being a Windows and MacOS user for a long time, this case-sensitive/insensitive difference is a PITA. I'm constantly making wrong typing in MacOS. and to avoid that, all _my folders/files_ are lowercase, just to avoid confusion.

I completely forgot about #167  which asks exactly the opposite . so now it's a deadlock 😢 .

Personally, I will keep the extension _completely case-insensitive_, and in the future, create a setting to the user be able to choose.

**Pull request merged**
