### PR TITLE
Multilanguage. Added English and Russian language.

### PR DESCRIPTION
**Pull request by Inter-Net-Pro**
To add a new language, need to create a file package.nls.{language}.json

### CODE REVIEW

**Comment by alefragnani** [comment]
Hi @Inter-Net-Pro ,

First of all, thanks for your PR 👍 (also in Bookmarks extension) .

What about the messages that the extension displays, like `The projects have been refreshed`? If I remember correctly, it needs additional code.

**Comment by alefragnani** [comment]
Having the commands translated is already a great addition. I asked about the messages because I remembered that when the VS Code team first released the internationalization support, it wasn't so easy to do.

I will try to find additional info about it, and update the extension if necessary.

Thanks

**Comment by alefragnani** [comment]
Hi @Inter-Net-Pro ,

I'll merge your PR in the next release. Could you please give me the translations for this resources:

```json
    "projectManager.commands.addToFavorites.title": "Add to Favorites",
    "projectManager.commands.toggleProjectEnabled.title": "Disable Project",
    "projectManager.commands.saveFirstProject.title": "Save your First Project",
```

Thank you

**Comment by Inter-Net-Pro** [comment]
Here is translation:
    "projectManager.commands.addToFavorites.title": "Добавить в избранное",
    "projectManager.commands.toggleProjectEnabled.title": "Отключить проект",
    "projectManager.commands.saveFirstProject.title": "Сохраните свой первый проект",

I think that you need to add to the file README section **translations into languages** and indicate there that the extension can be translated into different languages and give the path to the original file in English (make a small instruction). Then users from China, India and others will see about this opportunity and will be able to make and add to the repository translations into their native languages.

**Comment by alefragnani** [comment]
Hi @Inter-Net-Pro ,

Yes, it will have it in the future, but the first step is to add the basic/first translations 😄 

I have to ask you these new resources because it has been added to the extension after you created the PR, and I didn’t want to use Google Translator or similar tools, on this first release. 

I’m not sure how to deal with new resources yet. 

1. Use Google Translator/similar tool
1. Leave untranslated, waiting for PR
1. Leave untranslated, opening issues AND waiting for PR

Thank you

**Comment by Inter-Net-Pro** [comment]
If in localization file for some language there is no translation for some value, then VSCode will take the value from the default file package.nls.json
Therefore, it will not interfere with the development, modification and addition of new values to localization.

**Comment by Inter-Net-Pro** [comment]
Perhaps something will help:
I now also do localization for my chrome browser extension.
I have just registered at https://poeditor.com. There is a free subscription available and it is written that it supports format JSON. While I understand how this service works.
If you place your localization on this or any other similar service, you are ready to join and maintain localization in Russian.
If services do not suit you, then I will follow the changes in file 
package.nls.json and supplement translation into Russian through githab.

**Comment by alefragnani** [comment]
Thanks for your suggestion. I'll keep it noted 👍 

The new release should be available in the weekend. Stay tuned

**Pull request merged**
