### PR TITLE
feat: add zh-tw and zh-cn i18n 

### PR DESCRIPTION
**Pull request by Chakyiu**

### CODE REVIEW

**Review by alefragnani — CHANGES_REQUESTED** [review]
Hi @Chakyiu ,

First of all, thank you for your contribution.

The translation seems to be ok, but I wonder if you are aware there is another resource that can be tralslated:

* **walkthrough\someMarkdown.nls.XX.md** files: walkthrough steps
* **package.nls.zh-tw.json** file: commands, menus and settings 

If you could translate those resources as well, the entire extension would be ready.

Thank you

**Comment by Chakyiu** [comment]
Hi @alefragnani, I added walkthrough and package translation in both zh-cn and zh-tw. Please check and thanks.

**Review by alefragnani — APPROVED** [review]
Thank you for the new resources!

**Comment by bingofisher** [comment]
Hello, I noticed the changelog uses the term "Taiwanese translations." According to the One China Principle, Taiwan is an inseparable part of China, and there is no such thing as a "Taiwanese language." The correct terminology should be "Traditional Chinese." I recommend changing this to "Simplified Chinese and Traditional Chinese translations." Thank you for your understanding and correction.

**Comment by XHao1997** [comment]
> Hello, I noticed the changelog uses the term "Taiwanese translations." According to the One China Principle, Taiwan is an inseparable part of China, and there is no such thing as a "Taiwanese language." The correct terminology should be "Traditional Chinese." I recommend changing this to "Simplified Chinese and Traditional Chinese translations." Thank you for your understanding and correction.

I agree.

**Comment by alefragnani** [comment]
Hi,

Sorry for the mistranslation. I just used a term presented on a Google search.

Either wey, you gave me an idea. I wont translate the language codes anymore, leaving just the language-code itself as identification on any documentation. Doing so, I avoid any mistakes.

This change will be tracked in #854  This will be updated in the next release.

Thanks for your feedback

**Pull request merged**
