### PR TITLE
Correct spelling of setting with typo

### PR DESCRIPTION
**Pull request by apettenati**
Corrected spelling of the word `current` in the `openInCurrentWindowIfEmpty` setting.

### CODE REVIEW

**Comment by alefragnani** [comment]
Hi @apettenati ,

First of all, thank you for your PR.

My initial idea to fix #442 was _migrate_ the setting, but I guess a simpler `or` operator alternative, works pretty fine too.

Simply update `extension.ts` as suggested and I guess this could be available in the next release.

Thank you

**Comment by apettenati** [comment]
I've added the `or` to the config variable defined by this extension in the `extension.ts` file. Let me know if this is what you meant by your comment or if something else needs to be updated. Thanks.

**Comment by alefragnani** [comment]
Hi @apettenati ,

That's exactly what I mean, thanks!

But, while testing the PR, I just noticed an issue in the snippet I sent you, (my bad, sorry). 

VS Code is not properly indicating when a setting has no value defined. So, it is not considering the proper value for older/newer setting. 

This is not a big deal, since I could manage to solve it with a new piece of code. That being said, there is no reason to fix anything in your PR. I'll just apply a fix after merging it to the master branch.

Thanks again for your PR. This should be available in the next release (next month).

Thank you

**Review by alefragnani — APPROVED** [review]
Just as I comment, the first snippet I sent had some issues (my bad), so I had to do a small fix on that to properly identify older/newer values. 

The PR will be merged as is, and I'll apply this fix later.

Just out of curiosity, this is the new piece of code I had to use. I was forced to use the `Inspect` API to properly detect if the user has provided values to those settings, because the `get` API didn't differentiate between _default_ with _user provided_.

```ts
        const oldValue =  vscode.workspace.getConfiguration("projectManager").inspect("openInCurrenWindowIfEmpty");
        const newValue =  vscode.workspace.getConfiguration("projectManager").inspect("openInCurrentWindowIfEmpty");

        let config: string | unknown;
        if (oldValue.globalValue) {
            config = newValue.globalValue === undefined ? oldValue.globalValue : newValue.globalValue;
        } else {
            config = vscode.workspace.getConfiguration("projectManager").get<string>("openInCurrentWindowIfEmpty")
        }
```

Thank you

**Pull request merged**
